### ISSUE TITLE
The implementation doesn

### ISSUE THREAD

**Issue by NishanthVAnand** [kkhetarpal/ioc#1]
As per the description, with `1/3`rd of the probability, the agent is supposed to make the transition to a state in one of the 3 unintended directions. Essentially making a transition to one of the neighbouring unintended states with `1/9` probability. If this state is a wall, then the agent bounces backs to the original state.

However, this doesn't happen in the code. `empty_around()` function filters the wall states. Thereby picking the remaining feasible (non-wall) states with equal probability.

Example: Let's say the agent is in state `(1,1)` and takes action right (`3`). Accordingly, the agent moves to `(1,2)` with probability `2/3` (intended action), has to stay in the same state with probability `2/9` (due to hitting the wall and bouncing back), and move to `(2,1)` with `1/9` probability. 
`self.empty_around((1,1))` returns `[(2, 1), (1, 2)]`. `nextcell = empty_cells[self.rng.randint(len(empty_cells))]` picks one of these two cells with equal probability. Therefore, picking one unintended state with probability `1/6` instead of `1/9` and the state `(1,2)` with `5/6` probability.

**Comment by kkhetarpal** [comment]
Thanks for pointing this out, those are stale comments from previous baseline code, we have removed those comments in this commit [here](https://github.com/kkhetarpal/ioc/commit/fb88d5b881e0b5c317020b23874495e614b3ddc7).
